### ISSUE TITLE
Olefy Host 'olefy' is not accessible

### ISSUE THREAD

**Issue by waja** [tiredofit/docker-rspamd#12]
### Summary

Container doesn't start healthy.

### Relevant logs and/or screenshots

```
rspamd-1  | 2024-06-12.16:06:12 [WARN] ** [rspamd] Olefy Host 'olefy' is not accessible, retrying.. (5 seconds so far)
rspamd-1  | 2024-06-12.16:06:17 [WARN] ** [rspamd] Olefy Host 'olefy' is not accessible, retrying.. (10 seconds so far)
```
    
### Possible fixes

https://github.com/tiredofit/docker-rspamd/blob/baddf4e6093326c496b218a7ed1ffb1ebd0ae2dc/install/assets/functions/10-rspamd#L31 uses `${OLETOOLS_HOST}` `${OLETOOLS_PORT}` but 
https://github.com/tiredofit/docker-rspamd/blob/main/install/assets/defaults/10-rspamd has no defaults and https://github.com/tiredofit/docker-rspamd/blob/baddf4e6093326c496b218a7ed1ffb1ebd0ae2dc/README.md#environment-variables has not documentation about it.

**Comment by tiredofit** [comment]
`ENABLE_OLETOOLS=FALSE` should do it.

**Comment by waja** [comment]
Defining `${OLETOOLS_HOST}` and `${OLETOOLS_PORT}` also. But it would be great if:

- those values has defaults
- there will be documentation of the (default-)values

**Comment by waja** [comment]
#14 should fix this
