### ISSUE TITLE
Upgrade from 1.4.1 to 1.5x fails - rspamd keeps restarting: missing shared library libzstd.so.1 

### ISSUE THREAD

**Issue by Flunkyball** [tiredofit/docker-rspamd#7]
Hi,

I am running docker-rspamd without any issues in version 1.4.1.
After pulling the latest 1.5.1 or the version before 1.5.0 the container keeps restarting 50 times until the watch dog silences it.

According to the log messages the container fails to start due to a missing shared library "libzstd.so.1"

`rspamd-app      | Error loading shared library libzstd.so.1: No such file or directory (needed by /usr/bin/rspamd)
rspamd-app      | Error loading shared library libzstd.so.1: No such file or directory (needed by /usr/lib/rspamd/librspamd-server.so)
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_CCtx_setPledgedSrcSize: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_flushStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_initCStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_freeCCtx: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_compressStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_freeCStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_DStreamOutSize: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_CStreamInSize: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_DStreamInSize: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_createDStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_CCtx_reset: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_decompressStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_getDecompressedSize: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_initDStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_DCtx_reset: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_createCStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_isError: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_getErrorCode: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_freeDStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_getErrorString: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_compressBound: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_compress: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_getErrorName: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_createCCtx: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_endStream: symbol not found
rspamd-app      | Error relocating /usr/lib/rspamd/librspamd-server.so: ZSTD_compressStream2: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_compressCCtx: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_freeCCtx: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_DStreamOutSize: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_createDStream: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_decompressStream: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_getDecompressedSize: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_initDStream: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_isError: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_freeDStream: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_compressBound: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_getErrorName: symbol not found
rspamd-app      | Error relocating /usr/bin/rspamd: ZSTD_createCCtx: symbol not found`

**Comment by tiredofit** [comment]
Interesting. I don't see that on my systems, are you running something other than amd64 by chance? Arm64?

**Comment by tiredofit** [comment]
Hi, going to retract that I couldn't reproduce, I can now.

I have just built and pushed `1.6.0` which will solve the issue and also upgrade to RSpamd 3.4

**Comment by Flunkyball** [comment]
Thx for the fast analysis and solution.

I can confirm that 1.6.0 is working without any issues.
